version: '3'
services:
  customer_auth_db:
    image: 'postgres:10.1'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'p@ssw0rd'
      POSTGRES_USER: 'customer_auth'
      POSTGRES_DB: 'customer_auth'
    volumes:
      - customer_auth_db_data:/var/lib/postgresql/data
      - ./customer-auth/docker/postgresql/init.sh:/docker-entrypoint-initdb.d/init.sh
volumes:
  customer_auth_db_data:
